SELECT EXTRACT(YEAR FROM TRANS_DATE) AS YEAR, MAX(WITHDRAWAL_AMT) AS HIGHEST_AMT_DEBIT
FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM TRANS_DATE);


SELECT EXTRACT(YEAR FROM TRANS_DATE) AS YEAR, MAX(DEPOSIT_AMT) AS HIGHEST_AMT_DEPOSIT
FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM TRANS_DATE);


SELECT SUM(DEPOSIT_AMT) AS TOTAL_AMT_DEPOSIT, TO_CHAR(TRANS_DATE,'YYYY') AS YEAR
FROM BANK_TRANSACTION
GROUP BY TO_CHAR(TRANS_DATE,'YYYY') ORDER BY 2;


SELECT EXTRACT(YEAR FROM TRANS_DATE) AS YEAR, SUM(WITHDRAWAL_AMT) AS TOTAL_WITHDRAWAL_AMT
FROM BANK_TRANSACTION
WHERE TRANS_DATE LIKE '%19'
GROUP BY EXTRACT(YEAR FROM TRANS_DATE);


SELECT EXTRACT(YEAR FROM TRANS_DATE) AS YEAR, SUM(DEPOSIT_AMT) AS TOTAL_AMT_DEPOSIT
FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM TRANS_DATE);


SELECT DISTINCT(WITHDRAWAL_AMT) AS FIFTH_HIGHEST, YEAR
FROM(SELECT WITHDRAWAL_AMT, TO_CHAR(TRANS_DATE,'YYYY') AS YEAR, DENSE_RANK()OVER(PARTITION BY TO_CHAR(TRANS_DATE,'YYYY')ORDER BY WITHDRAWAL_AMT DESC) MAX_WITHDRAWAL_AMT
     FROM BANK_TRANSACTION)
WHERE MAX_WITHDRAWAL_AMT=5;


SELECT DISTINCT DEPOSIT_AMT AS SIXTH_HIGHEST, YEAR
FROM(SELECT DEPOSIT_AMT, TO_CHAR(TRANS_DATE,'YYYY') AS YEAR, DENSE_RANK()OVER(PARTITION BY TO_CHAR(TRANS_DATE,'YYYY')ORDER BY DEPOSIT_AMT DESC) MAX_DEPOSIT_AMT
     FROM BANK_TRANSACTION)
WHERE MAX_DEPOSIT_AMT=6 AND YEAR=2018;


SELECT COUNT(WITHDRAWAL_AMT)
FROM BANK_TRANSACTION
WHERE TRANS_DATE BETWEEN '5-MAY-18' AND '7-MAR-19';


SELECT DISTINCT WITHDRAWAL_AMT AS FIFTH_HIGHEST, YEAR
FROM(SELECT WITHDRAWAL_AMT, TO_CHAR(TRANS_DATE,'YYYY') AS YEAR, DENSE_RANK() OVER(PARTITION BY TO_CHAR(TRANS_DATE, 'YYYY')ORDER BY WITHDRAWAL_AMT DESC) MAX_WITHDRAWAL_AMT
     FROM BANK_TRANSACTION)
WHERE MAX_WITHDRAWAL_AMT=5 AND YEAR=2018;


SELECT DISTINCT DEPOSIT_AMT AS FIFTH_HIGHEST, YEAR
FROM(SELECT DEPOSIT_AMT, TO_CHAR(TRANS_DATE,'YYYY') AS YEAR, DENSE_RANK()OVER(PARTITION BY TO_CHAR(TRANS_DATE,'YYYY')ORDER BY DEPOSIT_AMT DESC) MAX_DEPOSIT_AMT
     FROM BANK_TRANSACTION)
WHERE MAX_DEPOSIT_AMT=5 AND YEAR=2019;

