SELECT TO_CHAR(TRANS_DATE,'MON') AS MONTH, COUNT(TRANS_DATE)
FROM BANK_TRANSACTION
WHERE TO_CHAR(TRANS_DATE,'YYYY')='2017'
GROUP BY TO_CHAR(TRANS_DATE,'MON')
ORDER BY TO_CHAR(TRANS_DATE,'MON');


SELECT DISTINCT DEPOSIT_AMT AS SECOND_HIGHEST, YEAR,MONTH
FROM(SELECT DEPOSIT_AMT, TO_CHAR(TRANS_DATE,'MM') AS MONTH, TO_CHAR(TRANS_DATE,'YYYY')AS YEAR, DENSE_RANK() OVER(PARTITION BY TO_CHAR(TRANS_DATE, 'MM')ORDER BY DEPOSIT_AMT DESC) MAX_DEPOSIT_AMT
    FROM BANK_TRANSACTION
    WHERE TO_CHAR(TRANS_DATE,'MM')=02 AND TO_CHAR(TRANS_DATE,'YYYY')=2018)
WHERE MAX_DEPOSIT_AMT=2;


SELECT MIN(DEPOSIT_AMT) AS LEAST_AMT
FROM BANK_TRANSACTION
WHERE TRANS_DATE LIKE '%APR_17';


SELECT SUM(DEPOSIT_AMT) AS TOTAL_DEPOSIT_AMT
FROM BANK_TRANSACTION
WHERE TO_CHAR(TRANS_DATE,'YYYY')=2017;


SELECT UNIQUE ACCOUNT_NO
FROM BANK_TRANSACTION
WHERE DEPOSIT_AMT=(SELECT MAX(DEPOSIT_AMT)
                   FROM BANK_TRANSACTION
                   WHERE TRANS_DATE LIKE '%19') AND TRANS_DATE LIKE '%19';