SELECT DISTINCT DEPOSIT_AMT AS SECOND_HIGHEST, YEAR
FROM(SELECT DEPOSIT_AMT, TO_CHAR(TRANS_DATE,'YYYY') AS YEAR, DENSE_RANK()OVER(PARTITION BY TO_CHAR(TRANS_DATE,'YYYY')ORDER BY DEPOSIT_AMT DESC) MAX_DEPOSIT_AMT
    FROM BANK_TRANSACTION)
WHERE MAX_DEPOSIT_AMT=2;


SELECT EXTRACT(YEAR FROM TRANS_DATE) AS YEAR, MAX(DEPOSIT_AMT)
FROM BANK_TRANSACTION
GROUP BY EXTRACT(YEAR FROM TRANS_DATE);


SELECT COUNT(UNIQUE ACCOUNT_NO) AS NO_OF_CUSTOMERS
FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT<20000 AND TRANS_DATE LIKE '%17';


SELECT COUNT(UNIQUE ACCOUNT_NO) AS NO_OF_CUSTOMERS
FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT>15000 AND TRANS_DATE LIKE '%FEB_17';


SELECT ACCOUNT_NO AS CUSTOMER_WITH_ACCOUNT_NO
FROM BANK_TRANSACTION
WHERE BALANCE_AMT=(SELECT MAX(BALANCE_AMT)
                   FROM BANK_TRANSACTION);
